title: Rodrigo Salmeron
description: Rodrigo Salmerón es un desarrollador web y diseñador gráfico.

name: Rodrigo Salmeron
markdown: kramdown
highlighter: rouge
permalink: /:collection/:title/

collections:
  portafolio:
    output: true
    permalink: /portafolio/:path/

google_analytics: "UA-58263416-1"
sass:
  style: compressed

gems:
  - jekyll-sitemap
